
all: NuclideChart.class

NuclideChart.class: EPSCreator.java EpsDocument.java EpsException.java EpsGraphics2D.java JIsotope.java NuclideChart.java RGBVector.java
	javac NuclideChart.java

cleanall:
	rm -rf *.class
	rm -rf *~